# Generated by Django 4.1.13 on 2024-01-05 17:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payer_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(max_length=20)),
                ('participants_ids', models.TextField(default='[]')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobileNumber', models.CharField(max_length=15)),
                ('balance', models.CharField(blank=True, max_length=10, null=True)),
                ('owe', models.CharField(blank=True, max_length=10, null=True)),
                ('to', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
